{% set name = "pandas-vet" %}
{% set version = "2023.8.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pandas_vet-{{ version }}.tar.gz
  sha256: ee6b80b40f5a74de41c29393e4dce373447b363faaa3e0677e4f36799ea865c3

build:
  noarch: python
  number: 2
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatch
    - hatch-regex-commit
  run:
    - attrs >=19.2.0
    - flake8 >6.0.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - pandas_vet

about:
  home: https://github.com/deppen8/pandas-vet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A flake8 plugin to lint pandas in an opinionated way
  dev_url: https://github.com/deppen8/pandas-vet

extra:
  recipe-maintainers:
    - deppen8
